@host = 127.0.0.0:8099

// Register User
POST http://{{host}}/api/register HTTP/1.1
content-type: application/json
    
{
    "first_name": "Kuuquish",
    "second_name": "Muuqish",
    "username": "kuuquish.muuqish",
    "email": "kuuquish@go.com",
    "password": "123465789"
}

###