@host = 127.0.0.0:8099

// Register User
POST http://{{host}}/auth/register HTTP/1.1
content-type: application/json
    
{
    "first_name": "Ooshish",
    "second_name": "Myrgiz",
    "username": "ooshish.myrgiz",
    "email": "mooshish@go.com",
    "password": "123465789"
}

###